### ISSUE TITLE
[Feature request] Supports diagnostics

### ISSUE THREAD

**Issue by FDiskas** [pucelle/vscode-css-navigation#10]
I know that this would be to much and probably out of the scope of the plugin. But what if.... :)
What if plugin not found classes in html code mark them as a gray color

![image](https://user-images.githubusercontent.com/468006/57452302-1bcd8900-726c-11e9-872a-4461272f25da.png)

For example that marked class is not found in any css files and it's probably unstyled. Mark it as error or grey color

:octocat:

**Comment by pucelle** [comment]
Hi, FDiskas, Thanks for your suggestion.
I think this would be very useful and interesting, I will research on it later when I have time to work on this plugin.

**Comment by pucelle** [comment]
This requires a big change, I'm working on some other functionalities which will be helpful to this, includes:
1. Supports  finding more resources in `@import ...` in CSS file.
2. Supports finding more resources in `<link href="...">`.
3. Supports loading remote resources.

Such that it should can make sure there is no class names missed for current document.

If you have some more suggestions, please note them here, Thanks.

**Comment by pucelle** [comment]
Postpone to October.

**Comment by pucelle** [comment]
Sorry, I started my new career as a graphic algorithm engineer these days, I will keep working on this plugin after my hard time over.

**Comment by LifeIsStrange** [comment]
@pucelle This is not the irght place, but I just wanted to thank you for this extension! This is the first that I've found to work for vue.js files

**Comment by pucelle** [comment]
Sorry, this feature will no be supported:
I didn't find an API to color something dynamically.
Otherwise, CSS is a magic thing, there always be some class names with existing only for fun.
And in technical reasons, it's nearly impossible to match strictly a html element with a css selector.

Nerver mind to reopen it if you have better idea and thanks so much.

**Comment by pucelle** [comment]
I wrote another plugin recently, and after some digging , now I think I can make this feature done according to vscode diagnostics API, and I also agree that it's important for some projects, in some scenarios, or at some time.

Work will be completed in one or two months, the whole time cost may be only a few hours, but sorry my daily work is really hard and busy.

**Comment by pucelle** [comment]
Will focus on completion, too complex to support diagnostics, and may cause may unexpected issues.

**Comment by pucelle** [comment]
Hi, [FDiskas](https://github.com/FDiskas), although 6 years have past.
After released V2.0 last year end, it makes it's possible to implement the class name diagnostic feature.
Here V2.6.0 has released, you can set `enableClassNameDiagnostic` to true to enable it. And please give me feedback about this feature if you'd like.
Thanks for your support.

**Comment by pucelle** [comment]
For more discussion and feedback, see https://github.com/pucelle/vscode-css-navigation/issues/107
