### ISSUE TITLE
VSCode Insaider

### ISSUE THREAD

**Issue by ArkIv** [pucelle/vscode-css-navigation#15]
а пропадает, даже из меню поиск определения
переустановлю - работает
закономерности нет.
может из за Remote-SSH ? 
но, если работает , то долго..
потом, почему-то - просто так , нет в меню "перейти к определению"

**Comment by pucelle** [comment]
Hi, Dear ArkIv, Sorry I can't understand Russian language, can you use English?

**Comment by pucelle** [comment]
If you don't mind, I will close this issue, please reopen it when you can give more details.
