### ISSUE TITLE
Highlighted CSS Rule Unreadable With Monokai Dimmed Theme

### ISSUE THREAD

**Issue by dfenton** [pucelle/vscode-css-navigation#16]
I use the Monokai Dimmed theme. With this theme, the highlighted CSS rule is practically unreadable due to the similarity between the orange background and font color. 

![image](https://user-images.githubusercontent.com/6623941/60304022-030a5700-9930-11e9-9b06-7bbf11f9f3e5.png)

I have modified Monokai Dimmed file to change all occurrences of this orange color to a color less bright but the CSS is still highlighted with the orange background. 

I would appreciate if you could explain how to change/remove this highlighting. 
Aside from that, I love your extension. It is so handy and speeds up my coding. 

Thanks

**Comment by pucelle** [comment]
Hi, dfenton, I just checked the configuration of VSCode, and found [this option](https://code.visualstudio.com/api/references/theme-color#peek-view-colors) should be what you are looking for.

If your theme plugin doesn't provide an option to modify it, you can also change your settings by adding:

```json
"workbench.colorCustomizations": {
	"peekViewEditor.matchHighlightBackground": "#Your preferred highlight color"
}
`
