### ISSUE TITLE
Add .twig to default activeHTMLFileExtensions

### ISSUE THREAD

**Issue by onetrev** [pucelle/vscode-css-navigation#17]
Just wondering if `.twig` should be added to the default list of `activeHTMLFileExtensions` since anytime you are dealing in twig there's a very good chance you have HTML mixed in there. No biggie if not, it's easy to just edit your list of extensions. All good!

**Comment by pucelle** [comment]
Yes, I will add `.twig` to the list. Thanks for your suggestion, onetrev.

**Comment by pucelle** [comment]
V1.6.3 was just released and supports `.twig` as default HTML file extension.

**Comment by onetrev** [comment]
Awesome! Very fast, thanks for that!
