### ISSUE TITLE
Can you add Turn off completion?

### ISSUE THREAD

**Issue by msacchetti** [pucelle/vscode-css-navigation#18]
In .vue files, this is the ONLY extension i found out of 20 that actually makes "peek/goto definition" work. Great! but... the autocompletion does not search other .vue files. So i use another plugin for autocompletion but the autocomplete from this plugin makes it not work.

Any way to disable the completion on this plugin but keep the peek/goto?

**Comment by pucelle** [comment]
Sure, I will on it later. Thanks for your feedback.

**Comment by pucelle** [comment]
Hi, dear msacchetti, V1.7.0 was just released and it supports enable or disable all the main functionality.

About parsing all CSS codes in `.vue` files and give completion service, I will work on it about one month later.

**Comment by pucelle** [comment]
Hi, msacchetti, I created another ticket https://github.com/pucelle/vscode-css-navigation/issues/19

Sorry I know nothing about `.vue` file type, can you list some scenarios (code pieces) that one `.vue` file needs the class names that defined in another `.vue` file. Such that I can add them to my test cases.

Thanks.

**Comment by msacchetti** [comment]
Thanks so much!

**After digging deeper i realize:**

About autocomplete in .vue files - opening up the Output console for this extension, i now see that autocomplete does not work at all in vue. It always returns: No completion found, 1 ms cost. _This is not even needed_ at all because the official vue extension for vs code does it already.

About goto/peek in .vue files -  goto/peek in vue files works fine (it shouldn't search other .vue files like i had said). It works in vue files because i have "search in <style> tags" turned on. 

So everything is actually working fine for me now in regards to autocompletion. I have a vue issue about scss files that i will open another ticket for.
