### ISSUE TITLE
JSX className autocompletion

### ISSUE THREAD

**Issue by mmcmm** [pucelle/vscode-css-navigation#2]
This is a follow up #1  the "go to" works now, amazing, but the auto-completion doesn't seem to work, it works fine for .html files, better than the other "css classes auto-completion" extension, which was offering to many options. 

Thanks again for the great extension.

**Comment by pucelle** [comment]
The issue I created:　https://github.com/Microsoft/vscode/issues/70616

**Comment by pucelle** [comment]
The issues was resolved, finally I found it's a functionality, not a BUG. The completion doesn't show by default in the tag attribute value of JSX.

you may change settings: 
`"editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": false
    },`

or click `Ctrl + Space` to popup completion list manually.

**Comment by pucelle** [comment]
I added some descriptions about this problem to my README.
