### ISSUE TITLE
Goto/peek in .vue files does not work for nested Scss

### ISSUE THREAD

**Issue by msacchetti** [pucelle/vscode-css-navigation#20]
In vue files, if a class has a nested class inside of it, goto/peek just jumps down to the top of the style tag.

Attaching screenshot with comments to show where it goes.

![Screen Shot 2019-08-05 at 5 49 06 PM](https://user-images.githubusercontent.com/6233258/62499764-6eeea380-b7a9-11e9-80c9-b36c5d25392d.png)

**Comment by pucelle** [comment]
Good catch, I've tested and confirmed this bug, and will fix it soon. Thanks very much.

**Comment by pucelle** [comment]
V1.7.1 was just released, Please check if it's working now, Thanks.
