### ISSUE TITLE
can it go to definition by clicking the import link

### ISSUE THREAD

**Issue by craigcosmo** [pucelle/vscode-css-navigation#21]
```jss
import './homeProduct.scss'
```

I want to go that `scss` file when I click `go to definition`. Is it possible ?

**Comment by pucelle** [comment]
Sorry to reply late, I'm on vocation these days.
Yes, it's possible, and  seems there is no other plugin which handles css files imports.
I will implements this in next month, Thanks.

**Comment by craigcosmo** [comment]
Awesome, look forward to it

**Comment by pucelle** [comment]
Postpone to October.

**Comment by pucelle** [comment]
Sorry, I started my new career as a graphic algorithm engineer these days, I will keep working on this plugin after my hard time over.

**Comment by pucelle** [comment]
Just released v1.10.0, please check it, thanks.

**Comment by craigcosmo** [comment]
how do you activate this feature?

**Comment by pucelle** [comment]
Automatically active, if not, please paste your code example.

**Comment by dwelle** [comment]
Yea, it doesn't work for me either:

```
import "./someFile.scss";
```

**Comment by pucelle** [comment]
Are you working in typescript codes? The import functionality only works in `<link href="...">` or `@import "..."`.

**Comment by craigcosmo** [comment]
I'm working basic react app, initiate with create-react-app.

```
components
    Home.js
    home.scss
```

Home.js
```js
import React from 'react'
import './home.scss'
const Home = ({
}) => {
	<div>hello</div>
}

```

**Comment by craigcosmo** [comment]
> Automatically active, if not, please paste your code example.

https://github.com/craigcosmo/my-app

try open the app.scss with jump

**Comment by dwelle** [comment]
> Are you working in typescript codes? The import functionality only works in `<link href="...">` or `@import "..."`.

I see, I thought it works in js/ts as well according to OP :).

**Comment by pucelle** [comment]
You are right, can't open, I thought that vscode should automatically opening css files from a ts or js file when goto definition, but it doesn't!

I will support this in this weekend.

**Comment by dwelle** [comment]
Thanks! In case you'll need to hardcode the extensions, let's enable it for `js`, `jsx`, `ts`, and `tsx` (maybe `svelte` and `vue` too?).

**Comment by edouard-lopez** [comment]
> You are right, can't open, I thought that vscode should automatically opening css files from a ts or js file when goto definition, but it doesn't!
> 
> I will support this in this weekend.

That's great news! :heart: 

The following [stackoverflow question](https://stackoverflow.com/q/40056990/802365) is exactly on this topic, so many people will be pleased !

**Comment by pucelle** [comment]
This should works now, sorry I was trapped into an algorithm problem these days and fix this too late.
And also thanks for you patience.

Never mind to give more suggestions and feedback.
