### ISSUE TITLE
Not working in react application

### ISSUE THREAD

**Issue by JiDai** [pucelle/vscode-css-navigation#22]
Hi,

I just created a react app with create-react-app. I tried to use the go to definition feature but VSCode did not find any definition in `className` : 

```function App() {
  return (
    <div className="App">

    </div>
  );
```

If I try to force completion in `className` attribute it does not work either.

Workspace symbols are working.

The plugin is well installed and VSCode is restarted.
VSCode and the plugin are up to date.

**Comment by pucelle** [comment]
Hi, JiDai, Sorry I'm on vocation these days, I will start to handle this issue from tomorrow, Thanks.

**Comment by pucelle** [comment]
Hi, JiDai, Version 1.7.2 was just released and it should work now.

The plugin has already supported parsing `jsx` class names but I didn't realize that `jsx` syntax can work in `js` files. So now the plugin will also parse `jsx` class names for `js` files.

Thanks.

**Comment by JiDai** [comment]
Thanks it works. 
But when I try to `Find all refercences` from a CSS declaration, the search results does not contain the `js` file but only the HTML files using the class.

**Comment by pucelle** [comment]
Few person care about the `Find all references`, so it doesn't support `JSX` syntax yet.
I created another issue about this: https://github.com/pucelle/vscode-css-navigation/issues/23, and scheduled to about 20th of September.

**Comment by JiDai** [comment]
Ok, for me this feature is very useful :)
Thanks for all 👍
