### ISSUE TITLE
Allow to include glob patterns

### ISSUE THREAD

**Issue by garyking** [pucelle/vscode-css-navigation#24]
I've got the following in my React code:

```js
import 'bootstrap/dist/css/bootstrap.css';
import '@fortawesome/fontawesome-free/css/all.css';
```

So I want to include those CSS definitions with this extension. But it's not possible, since, if I want to exclude `node_modules`, then these get excluded, too.

So, please make it possible to override some exclude rules with additional include rules. For instance, in `.gitignore`, I could do the following:

```
**/node_modules/**

!**/node_modules/bootstrap/**
!**/node_modules/@fortawesome/**
```

The above code would ignore `node_modules`, but then include the two dirs I want.

**Comment by pucelle** [comment]
Thanks for your suggestion, This will be included as part of next release, at the end of October.

**Comment by garyking** [comment]
Any updates on this? Thanks.

**Comment by pucelle** [comment]
Hi, garyking, Sorry but I start my new career as a graphic algorithm developer recently, I will continue working on the plugin after I tide over the hard time...

**Comment by pucelle** [comment]
Hi, garyking, I rechecked this ticket this morning, and I make sure this is a good idea and really useful, So I implement it soon.

Sorry I don't have much time to test it carefully and add a test case, please help to check it, Thanks.
