### ISSUE TITLE
Commented out ruleset within multiple selectors is included in definitions

### ISSUE THREAD

**Issue by aquaductape** [pucelle/vscode-css-navigation#25]
I'm not sure if this should be an issue since no one(except me because I'm clumsy) keeps commented out rulesets in between selectors.
![Screenshot from 2019-10-10 07-58-57](https://user-images.githubusercontent.com/29286430/66581555-2353cf80-eb35-11e9-8476-b35e97af7818.png)

**Comment by pucelle** [comment]
Hi, aquaductape, Thanks for your feedback.
No, you are not clumsy, this is a bug of my Sass parser, It wrongly parsed comment lines.

I will fix this soon, Thanks very much.

**Comment by pucelle** [comment]
I just released V1.7.3, and it may solve this problem.

The issue happens because I didn't expect the Scss declaration was commented betweens selectors.
