### ISSUE TITLE
Error thrown during init

### ISSUE THREAD

**Issue by s4m0r4m4** [pucelle/vscode-css-navigation#26]
I get the following error when I try a CSS auto-complete for the first time:

[9:01:27] c:\AIMDev\Projects\StreamlinedActiveLearning\Web\sal-angular-client\node_modules\@angular\material\_theming.scss tracked
[Error - 9:01:28 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Timer "${name}" is not started
  Code: -32603 

The plugin seems to work ok after that, but I figured I would pass it along.

**Comment by pucelle** [comment]
I will check it. Thanks very much.

**Comment by pucelle** [comment]
Normally this error should not happen. I made a fix to warn it, not throws any more. Will release at next version.

Thanks.
