### ISSUE TITLE
Not working searchAcrossWorkspaceFolders : false

### ISSUE THREAD

**Issue by fakhamatia** [pucelle/vscode-css-navigation#28]
I set `searchAcrossWorkspaceFolders` `False` but its search in other folders in the workspace.

current path `mobotix/tableMatch.php`

![Screenshot from 2019-10-25 11-21-32](https://user-images.githubusercontent.com/20030910/67553267-a4a48800-f719-11e9-9fbe-7cb14c13a309.png)

**Comment by pucelle** [comment]
Hi, fakhamatia, sorry to reply you late, the `searchAcrossWorkspaceFolders` is false by default, so the results should not be affected by changing the option.

Can you check you `mobotix` directory to make sure if you have included the other directories that listed here unexpected, for example, you linked them into your `mobotix`  directory.

Thanks.

**Comment by fakhamatia** [comment]
Hi @pucelle 
I'm sure because I renamed all folders in the workspace after that day. if I linked some folders now must not work anymore.
Here a screenshot for find definition (F12) `col`, its search in all Bootstrap and CSS files.
![Screenshot from 2019-11-09 11-20-47](https://user-images.githubusercontent.com/20030910/68525321-99d71f00-02e5-11ea-99e9-43519767d5a5.png)

**Comment by pucelle** [comment]
Hi, @fakhamatia, I just released version `1.9.0` and add more messages to debug.
Can you update the plugin and click `Ctrl + Shift + U`, and toggle to `CSS Navigation`, capture log messages (not need all, only several lines at the start would be OK) and print them here?

**Comment by fakhamatia** [comment]
I updated this morning.
[I don't have `Ctrl+Shift+U`](https://github.com/Microsoft/vscode/issues/36109) you mean output tab?

> [13:30:58] Client for workspace folder "html" started
[13:31:04] Server for workspace folder "html" started
[13:39:51] /var/www/html/HuChOp/dist/css/adminlte.css tracked
[13:39:51] /var/www/html/HuChOp/dist/css/adminlte.min.css tracked
[13:39:51] /var/www/html/HuChOp/dist/css/konectLogin.css tracked
.
.
.
[13:39:52] /var/www/html/VhANPR/vendor/whirl/whirl.min.css loaded
[13:39:52] /var/www/html/VhANPR/vendor/bootstrap/bootstrap-rtl.css loaded
[13:39:52] /var/www/html/VhANPR/vendor/simple-line-icons/css/simple-line-icons.css loaded
[13:39:52] 337 files loaded in 735 ms
[13:39:52] 8 definitions found, 872 ms cost

**Comment by pucelle** [comment]
It seems that your root workspace folder is `/var/www/html`, and it should be correct that if all the searched results are in the folder.
If you do need to filter out some search results, Please reference to the `excludeGlobPatterns` and `ignoreFilesBy` option.
