### ISSUE TITLE
VS Code language service will fail if the root directory name includes `[` or `]`

### ISSUE THREAD

**Issue by kanlukasz** [pucelle/vscode-css-navigation#29]
Hi,
I'm trying to use this extension and can't understand why it doesn't work
I added a project folder, there is an HTML file and a CSS file, but it still doesn't work

![obraz](https://user-images.githubusercontent.com/30685349/68596527-abfabe00-049b-11ea-8129-79dc99892a54.png)

#### My environment:
```
Version: 1.40.0 (system setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

May i ask you to help me with this issue?
What other information do you need from me?

**Comment by pucelle** [comment]
Hi, kanlukasz.
Do you mind to package your codes and sent it to me for testing?

**Comment by kanlukasz** [comment]
Thank for reply.
No problem, it's completely initial project

I uploaded files here:
https://github.com/kanlukasz/test

**Comment by pucelle** [comment]
I've tested the codes but it works for me...
Have you restarted your vscode after installed the plugin, If not, try it.
If it still can't work, open `settings.json` and lookup the properties starts with `CSSNavigation.`, to see if something wrong, or you can paste them here.
If still can't work... I don't know what to handle it, may be the only rest way is to remote connect with TeamViewer.

**Comment by kanlukasz** [comment]
Have you tested it on a Windows computer? I am asking because I had a similar problem with the TodoTree plugin, where everything works fine on Linux but not on Windows. This was due to globe patterns.

Anyway, I think I found the problem - it's about the path.

If project is in: `C:\Users\username\Desktop\[PR] wzgf 2020 - Kopia\www\web` - **not working**

If i change folder name from `[PR] wzgf 2020 - Kopia` to `abc` - **working fine**

Here is the package with this folder structure https://github.com/kanlukasz/test/blob/master/%5BPR%5D%20wzgf%202020%20-%20Kopia.7z

Could you test it?

**Comment by pucelle** [comment]
Windows is my only environment, I will test it in this weekend, Thanks.

**Comment by kanlukasz** [comment]
> 
> 
> Windows is my only environment, I will test it in this weekend, Thanks.

Sorry to bother you, but have you tested this issue?

**Comment by pucelle** [comment]
Sorry, I'm busy at a webgl project and totally forgot this...
I'v test the package you uploaded and rename it repeatedly to check if works, and my result is: VS Code language service will fail if the root directory name includes `[` or `]`. You may specify another parent directory as root directory and include this one, then it gonna work.

**Comment by kanlukasz** [comment]
Thank you for the answer and test.
I change the title of this ticket to keep the issue clear
Maybe if you find some time in the future, you can fix it.
Good luck with your new project 😉

**Comment by pucelle** [comment]
Thanks very much, kanlukasz.

I will keep working on this plugin in the end of January, it's welcome if you have some good ideas or any troubles.

**Comment by pucelle** [comment]
Still don't know how to fix this... May be this is a vscode system issue.

**Comment by pucelle** [comment]
More details about this issue:
Language server started, extension log seems good:
```
[2020-12-07 17:08:50.986] [exthost] [info] ExtensionService#_doActivateExtension pucelle.vscode-css-navigation {"startup":true,"extensionId":{"value":"pucelle.vscode-css-navigation","_lower":"pucelle.vscode-css-navigation"},"activationEvent":"*"}
[2020-12-07 17:08:50.986] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/FF/Desktop/vscode/vscode-css-navigation/client/out/extension
[2020-12-07 17:08:51.138] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug 
```
But can't get calling back for `connection.onDefinition` and other APIs. Everything works well after removing `[]` from workspace folder.

**Comment by kanlukasz** [comment]
I wanted to help you identify the problem and created a [issue in VSCode repository](https://github.com/microsoft/vscode/issues/112002). Unfortunately, they closed this issue because there were no exact steps to indicate the problem

If you have some time and you know how to describe it to them in steps, maybe you can try to create such an issue in their repository.
I can't help more or debugging your code as I am only a PHP junior developer. Sorry 😞

**Comment by pucelle** [comment]
Sure, I will research more and give a minimum code example if it is definitely a vscode issue. Can't promise when...

**Comment by pucelle** [comment]
I'm also a junior PHP developer some years ago... never dive in.
