### ISSUE TITLE
Not working "CSSNavigation.alsoSearchDefinitionsInStyleTag": true

### ISSUE THREAD

**Issue by tomozo77** [pucelle/vscode-css-navigation#31]
I have defined one css.
This "CSS Navigation" displayed two css.
One of them is unrelated css.
And that css was picked up.
I corrected it by mistake.

I'm sorry, I'm not good at English, so I use translation software.
Thanks.

**Comment by pucelle** [comment]
Never mind, My English is not good too!

Bug sorry I can't exactly know what's happening from your message, It seems that you got a wrong definition after checked "CSSNavigation.alsoSearchDefinitionsInStyleTag".

Do you mind to paste some of your code pieces here?

**Comment by tomozo77** [comment]
Thank you for your reply.

    "CSSNavigation.alsoSearchDefinitionsInStyleTag": true,
    "CSSNavigation.excludeGlobPatterns": [],
    "CSSNavigation.activeCSSFileExtensions": ["css"],
    "CSSNavigation.activeHTMLFileExtensions": ["html"],

<link rel="stylesheet" href="style1.css?<?php echo filemtime('style1.css') ?>">

Thanks.

**Comment by tomozo77** [comment]
`<link rel="stylesheet" href="style1.css?<?php echo filemtime('style1.css') ?>">`

Thanks.

**Comment by pucelle** [comment]
Hi, tomozo77,I can't tell what's happening from codes you pasted. Can you take a screenshot about the plugin wrongly picked CSS definition and show what it picked and not picked?

You may also package some codes of you app and upload it if you don't mind.

Otherwise, when option `alsoSearchDefinitionsInStyleTag` checked, the plugin will search additional CSS definitions from `<style>...</style>`, not from `<link rel="stylesheet" href="style1.css...`.

**Comment by tomozo77** [comment]
![test](https://user-images.githubusercontent.com/60161223/72985992-8b030180-3e2a-11ea-9b36-3d2780f0bc87.jpg)
Thanks.

**Comment by tomozo77** [comment]
inline
![test2](https://user-images.githubusercontent.com/60161223/73031858-9ed95280-3e80-11ea-9aa3-70dd012966bc.jpg)
Thanks.

**Comment by tomozo77** [comment]
I installed this extension only on another PC.

When I ran it there, the results were the same.

Is it working properly on your PC?

**Comment by tomozo77** [comment]
It will take some time, so it will end once.
We expect for the next version up.
Thanks.

**Comment by pucelle** [comment]
Hi, tomozo77, Sorry about not responding you for days, we are on Chinese New Year vacation these days, And I'm just back to coding.

From the screenshots, everything works as expected, when `alsoSearchDefinitionsInStyleTag` checked, it searches CSS definitions from your current HTML file by the class name `top_lf`. If found, it will always be shown as the first selected (I can't control the order), although it may be not the right definition you want.

If you don't like it, just uncheck the `alsoSearchDefinitionsInStyleTag`. It's welcome if you have some questions or suggestions.

**Comment by tomozo77** [comment]
I'm sorry.
I was misunderstanding.

 I thought that "CSSNavigation.alsoSearchDefinitionsInStyleTag" should be searched first from "<link rel = stylesheet".

Thank you.

**Comment by pucelle** [comment]
Never mind.
