### ISSUE TITLE
[Feature] "Ignore Files By" Support '.cssignore'

### ISSUE THREAD

**Issue by xianghongai** [pucelle/vscode-css-navigation#33]
![cssingnore](https://user-images.githubusercontent.com/2075006/79642356-85218000-81cf-11ea-9b48-e01156ee8947.png)

THX

**Comment by pucelle** [comment]
Good suggestion, I will support it later.
By the way, Is there a standard about the ".cssignore", does it be widely accepted?

**Comment by xianghongai** [comment]
It won't be a standard, it's just a neglect of styles, and it's a relatively niche.

**Comment by xianghongai** [comment]
Are there any such extensions related to JavaScript? At present, most extensions are based on the module mechanism. For older projects like ES5, HTML and JS cannot map the reference relationship.

This CSS definition search is very powerful, thank you!

**Comment by pucelle** [comment]
As I know, No such plugins for JavaScript.

**Comment by pucelle** [comment]
Have no plan to do so, try option `excludeGlobPatterns`.
