### ISSUE TITLE
[request] Completion should also refer to style tag

### ISSUE THREAD

**Issue by shungo27** [pucelle/vscode-css-navigation#34]
If '"CSSNavigation.alsoSearchDefinitionsInStyleTag": true', Completion should also refer to style tag.

**Comment by pucelle** [comment]
Thanks for your catching, I will fix it but sorry I'm busy at a project, so I can't promise when.

**Comment by tuan-lm** [comment]
@pucelle  i am waiting for this feature as well. I'm using vue and i must said your extension is the only 1 can get the job done in vue files. Completion refer to style tag is the only missing piece left for this to be perfect to use with vue. It is a shame that your extension had fewer download than the others. Hope you can get some free time in the future to get this 1 done

**Comment by pucelle** [comment]
Thanks very much, tuan-lm.
Yes this plugin is very unique because I also implemented it's code parser, without using some very heavy and strict libraries.
I will come back to work as a web developer recently, so I will continue working on this plugin.

**Comment by pucelle** [comment]
v1.10.1 just released, please try it, thanks.

**Comment by tuan-lm** [comment]
Awesome work 🔥
