### ISSUE TITLE
alsoSearchDefinitionsInStyleTag does not work

### ISSUE THREAD

**Issue by rtonsing** [pucelle/vscode-css-navigation#37]
Using even this simple example, "Go to definition" shows "No definition found for 'center'"
"CSSNavigation.alsoSearchDefinitionsInStyleTag": true

<html>
<head>
  <style>
    .center { text-align: center; }
  </style>
</head>

<body>
  <div class="center">I should be centered</div>
</body>
</html>

**Comment by pucelle** [comment]
I guess, you may not include the test code into a work directory. Just drag the file or directory which include the HTML files into left vscode explorer as a workspace, and it should work then.

**Comment by rtonsing** [comment]
Seems weird to me, but it works.

**Comment by pucelle** [comment]
This plugin was designed to work only when in a workspace, I'm consider to make it work for any open files.
Never mind to give any suggestions.
