### ISSUE TITLE
Add "nolazy" parameter to the settings 

### ISSUE THREAD

**Issue by Curiouslynx** [pucelle/vscode-css-navigation#39]
Please add the "nolazy" parameter to the settings to start CSSNavigation anyway, because the extension doesn't work when I open a directory with no files open.

**Comment by Curiouslynx** [comment]
For example: I open or create a new project - and CSSNavigation does not work

**Comment by pucelle** [comment]
Basically this plugin (and also others) is started only when required, so it will not delay project startup.
Can you describe more details about what's problem you meet? Why you need it started immediately?

**Comment by Curiouslynx** [comment]
If I open a project (File->Open Directory...) with at least one document open for editing, then CSSNavigation works fine. And I can find the line "...css-navigation-1.9.0..." in the process list (highlighted in the attached screenshot).

But when I open the same directory and there is no open document for editing, and then create new file (or open any file for editing), the extension no longer works (and process "...css-navigation-1.9.0..." is missing).

![cssnavigation](https://user-images.githubusercontent.com/39624124/93014957-f66a3100-f5bd-11ea-9940-1b06c362cf15.png)

**Comment by pucelle** [comment]
Sounds like a bug... I will check it later.

**Comment by pucelle** [comment]
Should be repeat with #44.
Never mind to reopen it again if still exist after released.
