### ISSUE TITLE
Feature request: Respect .gitignore files

### ISSUE THREAD

**Issue by FDiskas** [pucelle/vscode-css-navigation#4]
Thanks for cool plugin. 
Just noticed, that plugin includes css files that are ignored in git. Thous css files are compiled from scss.

**Comment by pucelle** [comment]
Hi, DFiskas, Thanks for your concern.

I checked the files in directory but I can't find the CSS files you said. Do you mean this:
https://github.com/pucelle/vscode-css-navigation/blob/master/client/test/fixture/css/test.css

If so, This CSS file was just for E2E test, although it was compiled from Scss file, it's also useful:
https://github.com/pucelle/vscode-css-navigation/blob/master/client/test/src/file-tracking.test.ts#L53

It was used to test the `ignoreSameNameCSSFile` option, which can help to search in CSS file when Sass file with same name and in same directory is not exist.

If what you would to say is not so, please provide more information.

Thanks.

**Comment by FDiskas** [comment]
I mean that plugin by it's self scans for files and also is scaning ignored by gitignore

**Comment by pucelle** [comment]
OK, I understand now, sorry to misunderstand you.
I will implement this in one or two days.

**Comment by pucelle** [comment]
Hi, FDiskas, V1.3.0 was just released and should fixed this issue, please check it, Thanks.
Otherwise sorry for misunderstand you because English is not my mother language, I'm still learning it.

**Comment by FDiskas** [comment]
My English also not good, and it's not my native language to. :)

**Comment by pucelle** [comment]
☺

**Comment by FDiskas** [comment]
thanks

**Comment by FDiskas** [comment]
Did you tried some libraries? I wonder there is some cases where multiple gitignore files are located in idfferent folders.
This could help you https://www.npmjs.com/package/deglob

**Comment by pucelle** [comment]
Yes, You do find where the problems is!
Recently I only respect (I just learned this world from you😃) the `.gitignore` from the root directory.
I will work on it later soon.
Thanks very much.

**Comment by pucelle** [comment]
Hi, FDiskas, I researched a little on the code of `deglob` and found it only supports `.gitignore` in the root directory too.
I'm Sorry that I will not handle multiple `.gitignore` files before I got more feedbacks and user cases.
Otherwise Thanks for the suggestion.
