### ISSUE TITLE
Request textDocument/definition failed.  

### ISSUE THREAD

**Issue by 2234839** [pucelle/vscode-css-navigation#41]
// 我使用vue  当我开启CSSNavigation.alsoSearchDefinitionsInStyleTag 后含有
I use vue when I enable CSSNavigation.alsoSearchDefinitionsInStyleTag after containing

```
<style src="./goods.scss"></style>
```
// 这样的代码我就无法正常使用 css navigation ， 经测试主要是由于 style  块中没有包含任何代码的情况下报错如下
 I can't use css navigation with this code, but the test is that the style block doesn't contain any code and the error is as follows

```
Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
```

// 我期望能够支持无代码的情况,十分感谢
I look forward to supporting the no-code situation, thank you very much.

**Comment by pucelle** [comment]
Just released v1.10.1, please check it, thanks.
