### ISSUE TITLE
Ability to include a specific CSS file

### ISSUE THREAD

**Issue by kanlukasz** [pucelle/vscode-css-navigation#43]
Hello

I would like to get `Class Completion` from the original `Bootstrap framework CSS` file. Bootstrap files are in `node_module` directory. Is it possible to include bootstrap files to get class autocompletion in my project?

**Comment by pucelle** [comment]
Hi, try include the directory with a glob expression in `alwaysIncludeGlobPatterns` option, like `**/bootstrap/**`.
Otherwise, importing bootstrap files from your css codes like `@import bootstrap/xxx` will also force it work.
Any other problems, welcomes to feedback.

**Comment by tuan-lm** [comment]
I think this feature is not work. For example i'm using a framwork called "vuetify" and it's files in `node_module` directory also.
My setting as follow : 
```
"CSSNavigation.alwaysIncludeGlobPatterns": [
        "**/vuetify/**",
    ],
```
But 1 weird thing, if i open the file `vuetify.css`(which is in vuetify/dist directory ) in the editor then it actually work, but i can't manually go to node_modules and open it everytime i have to work.

**Comment by pucelle** [comment]
This should be a bug, I will check it later.

**Comment by kanlukasz** [comment]
https://github.com/pucelle/vscode-css-navigation/issues/44 can be related

**Comment by pucelle** [comment]
Should be same with #44.
