### ISSUE TITLE
1.10.1 disables some javascript snippets

### ISSUE THREAD

**Issue by BrettBedarf** [pucelle/vscode-css-navigation#46]
The past few days I've noticed some javascript snippets such as "for" to make a for loop stopped autocompleting or showing as a suggestion at all. When typing for + tab it just shows loading in the suggestion box:

![image](https://user-images.githubusercontent.com/25183985/101842460-50b75700-3b05-11eb-8fc6-2e688a985758.png)

While with CSS Navigation disabled, expected behavior, typing for in a js file, and autocomplete with tab:

![image](https://user-images.githubusercontent.com/25183985/101842582-9c6a0080-3b05-11eb-9556-750f06a4664d.png)

I'm surprised this is the culprit but I've disabled all extensions and re-enabled one by one (not fun), quadruple checked, etc.

Also confirmed 1.10.0 manual install no snippet issues.

**Comment by pucelle** [comment]
Thanks for your feedback, I will check this later.

**Comment by kanlukasz** [comment]
@BrettBedarf, please provide more details. This will help to verify the problem more effectively

1. What operating system are you working on?
2. What version of VSCode are you using?
3. Have you tried to reproduce this issue in a clean and fresh portable version of VSCode?
4. Have you tried to reproduce this problem without any additional settings in your `settings.json` file?

I'm trying to reproduce this problem on a **Windows 10 20H2** machine with **WSL2** and everything seems to work fine:
![gif2](https://user-images.githubusercontent.com/30685349/101897597-17392700-3bab-11eb-984c-13661ee20ac0.gif)

**Comment by pucelle** [comment]
1.10.0 have some issues and can't be started up... Sorry I tried to unpublish it but can't find a way.
I checked but can't reproduce this issue too.
I guess if everything works well, this plugin should never affect another plugin's snippet function.
Can you provide more infos as @kanlukasz  said?

**Comment by kanlukasz** [comment]
Hmm ... it's strange, but just now, this problem also happened to me. Snippets didn't work, but only for a moment.
Unfortunately I have not caught the cause yet.

Interestingly, at the same time, my virtual machine started using 95% of the CPU
@pucelle do you use any regex pattern there or something like ripgrep? Maybe it's part of the problem, or maybe VSCode itself has a problem? Hmmm, I think it will be hard to verify

**Comment by kanlukasz** [comment]
There is definitely something wrong
If i exclude `JS` from `CSSNavigation.activeHTMLFileExtensions` option, the snippet are starting to work

**Comment by pucelle** [comment]
Ok, I will check it.

**Comment by pucelle** [comment]
Found the bug in my code parsing classes, fixing it...

**Comment by pucelle** [comment]
V1.10.2 already released. please check it, thanks.
Sorry I made a infinite loop in my CSS code lexical analyzer.

**Comment by pucelle** [comment]
Thanks again for both of your helps.
