### ISSUE TITLE
Is preloadCSSFiles option avaiable  

### ISSUE THREAD

**Issue by tuan-lm** [pucelle/vscode-css-navigation#48]
In the **Why started this project** section i see you mention about the `preloadCSSFiles` option.
But i don't see you descript how to use them
And if i try to use them in the settiong file like this "CSSNavigation.preloadCSSFiles", vscode will said that this is an `Unknown Configuration Setting`
I just wonder if this option even avaiable

**Comment by pucelle** [comment]
Sorry, this option is not available any more, the description should be changed I will change it soon.
Never mind to give your feedbacks.

**Comment by tuan-lm** [comment]
Very well. I just ask this question because the extension won't  start suggesting css class when i first open vscode, i have to force it by `Ctrt + .` and then wait a bit to get it start suggesting. But i don't think it's that much of a problem so i will close this issue

**Comment by pucelle** [comment]
Yes the CSS service start up with a delay.
My development work doesn't startup new vscode window frequently, and I guess few people would set this option, and a quick started CSS service would delay the vscode initializing. That's whey I removed this option.
