### ISSUE TITLE
Build Documentation

### ISSUE THREAD

**Issue by kdumontnu** [pucelle/vscode-css-navigation#51]
Can you add documentation to build/contribute?

I'm getting the following error when I try to start with `npm install`:
```
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "github:pucelle/ignore-walk": name can only contain URL-friendly characters
```

**Comment by pucelle** [comment]
OK, I will fix this soon.

**Comment by pucelle** [comment]
Try again.

**Comment by kdumontnu** [comment]
The error above is resolved, but I still get many type errors when I run `npm run build`:

```
...
server/node_modules/vscode-languageserver/lib/main.d.ts:477:35 - error TS2314: Generic type 'NotificationType<P>' requires 1 type argument(s).

477     sendNotification<P, RO>(type: NotificationType<P, RO>, params: P): void;
                                      ~~~~~~~~~~~~~~~~~~~~~~~

server/src/languages/jsx/jsx-scanner.ts:4:9 - error TS2614: Module '"../../../node_modules/vscode-uri/lib/umd"' has no exported member 'URI'. Did you mean to use 'import URI from "../../../node_modules/vscode-uri/lib/umd"' instead?

4 import {URI} from 'vscode-uri'
          ~~~
...
```

Perhaps if you commit your `package-lock.json` file so that I can use the same package versions?

**Comment by pucelle** [comment]
Checked in package-lock.json, try again.

**Comment by kdumontnu** [comment]
That resolved many of the errors, but I think you need to update `vscode-uri` in `./server/package.json` to the latest version to get rid of `error TS2614: Module '"../../../node_modules/vscode-uri/lib/umd"' has no exported member 'URI'.`

**Comment by pucelle** [comment]
I've upgraded version of `vscode-uri`, sorry it's in wrong version before.
