### ISSUE TITLE
[Feature Request] Expanded cross file type completion

### ISSUE THREAD

**Issue by onetrev** [pucelle/vscode-css-navigation#55]
While there are other extensions that provide either _CSS/SCSS to CSS/SCSS_ and _HTML/PHP to CSS/SCSS_ autocompletion, it would be awesome if CSS Navigation could do it all (because it already is the best at CSS->HTML autocompletion). I imagine there might be a performance hit for this, especially for large workspaces, so a way to disable this functionality for those that don't want it would be good.

If I had to pick between the two, I'd easily pick [HTML to CSS](https://marketplace.visualstudio.com/items?itemName=solnurkarim.html-to-css-autocompletion) autocompletion. My guess is a lot of users could use this functionality. I think a pretty common workflow is to create your markup, including the class name, then go into your CSS/SCSS files and add the class.

**Comment by pucelle** [comment]
Well, this is a very good feature, why I didn't find it earlier...

And don't worry, this is no potential performance issue expect it requires a litter longer time to startup CSS Navigation service.

The feature may cost me a whole day or 2 to implement, and I have a busy daily work, so I can't  promise when.

**Comment by onetrev** [comment]
Awesome, glad to hear you will consider adding this. No rush, it will nice to have whenever it lands. Thanks!

**Comment by onetrev** [comment]
Hi @pucelle ... No worries at all, I know you build this all on your own time, but I just wanted to check in to see if you were still thinking of adding the requested functionality? Let me know if you need me to test it or whatever -- if you do end up doing this.

**Comment by pucelle** [comment]
Hi, @onetrev , I'm still here, never left.

Sorry for the development plans are always behind schedule, I've paid all my time to a rendering system recently, which is a big challenge to me.

Yes I definitely will implement this feature, please be patient, and thanks.

**Comment by pucelle** [comment]
Meet same requirement, will work on it soon.

**Comment by pucelle** [comment]
v1.13.0 was just released, now should support custom element tag names, class names, ids auto completion.

**Comment by pucelle** [comment]
v1.13.1 is the right version.

**Comment by onetrev** [comment]
Hello @pucelle ! This is very exciting you were able to get around to this. Thank you! However, I'm finding it's throwing errors for me. This is the output from the panel:

```
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Error - 1:48:24 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property '0' of undefined
  Code: -32603 
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Warn  - 1:48:24 PM] [13:48:24] Unhandled Rejection: TypeError: Cannot read property '0' of undefined
[Error - 1:48:24 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property '0' of undefined
  Code: -32603 
[Error - 1:48:26 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property '0' of undefined
  Code: -32603 
```

To create this all I did was open up a `.scss` file and tried to activate the intellisense / autocomplete.

Let me know if there's anything further I can do to troubleshoot.

**Comment by pucelle** [comment]
Will handle it!

**Comment by pucelle** [comment]
I think I found the cause of the problem, will fix it soon.

**Comment by pucelle** [comment]
Try the new version v1.13.2.

**Comment by onetrev** [comment]
I tried it... Works perfectly! Thank you many times over for getting this HTML->CSS completion added to the extension.
