### ISSUE TITLE
Request textDocument/completion failed with message: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by kanlukasz** [pucelle/vscode-css-navigation#56]
### Issue description:

The plugin returns a warning and an error when i start to work with my project.
At first glance, this only happens once when I start working with code.

The `Output` from CSS Navigation looks like this:

```
[18:25:37] Client for workspace folder "public_html" started
[18:25:37] Server for workspace folder "public_html" started
[Warn  - 6:38:09 PM] [18:38:09] Timer "track" is not started
[Error - 6:38:09 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'length' of null
  Code: -32603 
```

### Plugin settings:
```
"CSSNavigation.activeCSSFileExtensions": [
    "css",
    "scss"
],
"CSSNavigation.activeHTMLFileExtensions": [
    "html",
    "php"
],
"CSSNavigation.alwaysIncludeGlobPatterns": [
    "**/node_modules/bootstrap/dist/css/bootstrap.css"
],
"CSSNavigation.excludeGlobPatterns": [
    "**/wp-content/themes/project/assets/css/**",
    "**/node_modules/**",
    "**/bower_components/**",
    "**/vendor/**",
    "**/coverage/**"
],
```

### My environment:
- Windows 10 20H2
- WSL2 (Ubuntu 20.04)
- VSCode 1.54.3 
- CSS Navigation 1.10.5

**Comment by pucelle** [comment]
Hi, kanlukasz , can you provide some code examples which will raise the error?

**Comment by kanlukasz** [comment]
I tested it with this code:

```
<div class="col-12 col-md-4 my-3 my-md-0">
    <div class="d-flex justify-content-center align-items-center h-100 bg-light rounded p-2">
        <span class="font-weight-bold text-danger">INFOLINE</span>
    </div>
</div>
```

It is difficult to create a step-by-step description of the problem because it doesn't happen every time.

I tested it again and found it happens when I don't wait a moment after starting or reloading VSCode and start typing a css class right away

Looks like something is not loading at the very beginning?


![image](https://user-images.githubusercontent.com/30685349/112289047-3bb69c00-8c8e-11eb-9331-a0814ec4ce60.png)

**Comment by pucelle** [comment]
Thanks, I will look at it later.

**Comment by Cronkan** [comment]
In my case it was because of a *.min.css file. Fixed it by adding this:
```json
  "CSSNavigation.alwaysIncludeGlobPatterns": ["**/node_modules/bootstrap/dist/css/!(*min.css)"],
  "CSSNavigation.excludeGlobPatterns": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/vendor/**",
    "**/coverage/**",
    "**/*.min.css"
  ]
  ```

**Comment by pucelle** [comment]
I've checked,

**Comment by pucelle** [comment]
Temporary closed, never mind to reopen it.
