### ISSUE TITLE
A dash separates the active link of the CSS class

### ISSUE THREAD

**Issue by kanlukasz** [pucelle/vscode-css-navigation#57]
I'm not sure if it's because of VSCode API or settings, but I've been noticing for a while that the dash separates the active link of the CSS class.
The easiest way to show it is on a video gif. I attached below

![gif45](https://user-images.githubusercontent.com/30685349/112290793-dc598b80-8c8f-11eb-9c61-5d1b75c609a5.gif)

Should it work like this?

### My environment:
- Windows 10 20H2
- WSL2 (Ubuntu 20.04)
- VSCode 1.54.3 
- CSS Navigation 1.10.5

**Comment by pucelle** [comment]
I guess this should come from another plugin, or a vscode setting, my vscode environment with "CSS Navigation" on doesn't look like this.

**Comment by kanlukasz** [comment]
Ok, you are right. This is due to the `editor.wordSeparators` parameter setting.
