### ISSUE TITLE
[Feature Request] Support array value

### ISSUE THREAD

**Issue by Ttou** [pucelle/vscode-css-navigation#59]
hope array value can work

```jsx
<div class={['main', { show: this.show }]}></div>
```

**Comment by Ttou** [comment]
**you can implement it like this**

![image](https://user-images.githubusercontent.com/4298437/127482860-aeca3e1d-980d-40bc-abf5-377dc7228131.png)

**Comment by pucelle** [comment]
For the long term, will implement a new syntax parser instead of only parsing character tokens. It will cost some time.

**Comment by VadimKalinin** [comment]
Pucelle, I don’t navigate to css from this jQuery selector: $(‘#id-name1 .class-name1 input[checked:true]’), for each part of this selector. Is this possible in future?
Thank you for your answer, with best regards, Vadim

**Comment by pucelle** [comment]
In fact, It can be done, but not easy, it should be separated into 3 levels:

1. Navigate to all the `input[checked:true]` selectors in CSS files, this is what can be done easily right now.
2. Navigate to the right `#id-name1 .class-name1 input[checked:true]`, with all the parent selectors match. difficult, have a plan to do so (and also a feature request https://github.com/pucelle/vscode-css-navigation/issues/50).
3. I just guess, may the selector should be navigated to HTML tags? or both HTML tags and css selectors.

**Comment by VadimKalinin** [comment]
Thank you, Pucelle, for your answer. I will wait for the new syntax parser implementation. Good luck with this task

**Comment by pucelle** [comment]
Released v1.11.0, goto definition and auto completion for `<div class={['main', { show: this.show }]}></div>` should work now. (Finding references is not fully supported, need some time to develop and may not useful enough).

Otherwise,  jQuery selectors like  $(‘#id-name1`), $(`.class-name1`) should work too, but it matches only one selector, ignores nesting.
