### ISSUE TITLE
不能跳转.less文件

### ISSUE THREAD

**Issue by zhanghenvom** [pucelle/vscode-css-navigation#61]
"CSSNavigation.ignoreSameNameCSSFile": true；
    "CSSNavigation.activeCSSFileExtensions": [
        "less",
        "scss",
        "css"
    ]

 大佬，如果一个文件里有less和cs文件，只会跳转到css文件，是我没设置对吗

**Comment by zhanghenvom** [comment]
> "CSSNavigation.ignoreSameNameCSSFile": true；
> "CSSNavigation.activeCSSFileExtensions": [
> "less",
> "scss",
> "css"
> ]
> 
> 大佬，如果一个文件里有less和cs文件，只会跳转到css文件，是我没设置没对吗

**Comment by pucelle** [comment]
Just released v1.11.1 to fix an issue which will cause css files not to be ignored when the same name less file exists.
Sorry, have no chance to test all less features.
