### ISSUE TITLE
It doesn`t work if you make line break in opening tag.

### ISSUE THREAD

**Issue by Rusl10** [pucelle/vscode-css-navigation#62]
Hello. You can see the bug in the video.

https://user-images.githubusercontent.com/26712091/141613529-841b1ab8-2db7-4d2f-84a7-68206c58840e.mp4

P.S. The same problen in html files too.
Thanks.

**Comment by pucelle** [comment]
Thanks for your video, will fix it soon.

**Comment by pucelle** [comment]
Fixes this at v1.11.2.

**Comment by Rusl10** [comment]
It works! Thanks!
