### ISSUE TITLE
Does not see .sass files

### ISSUE THREAD

**Issue by alukardark** [pucelle/vscode-css-navigation#63]
Hello, will there be support for .sass (no brackets)? At the moment, only .scss works.

https://user-images.githubusercontent.com/7904596/142765313-9e33d376-7743-44fd-bfeb-ebaf44826a4a.mov

**Comment by pucelle** [comment]
Yes, doesn't support sass syntax without bracket, this is definitely a problem, but got few feedback, I guess there should be not many developers using the sass syntax without bracket.

Will implement this when I have some time. Thanks.

**Comment by pucelle** [comment]
v1.12.1 was released, you may try if there are bugs that existed with sass syntax.
