### ISSUE TITLE
if use  dash to connnet class word, will show two result, if use underlne ,then only one 

### ISSUE THREAD

**Issue by awkj** [pucelle/vscode-css-navigation#64]
![image](https://user-images.githubusercontent.com/9017743/146627354-9b7df828-014e-4d0b-be28-cd264fd59174.png)
![image](https://user-images.githubusercontent.com/9017743/146627355-73493b06-6175-49ca-acbe-1d85897ba2fe.png)
![image](https://user-images.githubusercontent.com/9017743/146627358-b35b9b15-854f-43a4-a62b-de681185d9a1.png)

can I set dash style class as one class, and jump ?

**Comment by pucelle** [comment]
Does the two definition results at the same file, and same position?

**Comment by awkj** [comment]
> Does the two definition results at the same file, and same position?

Yes

**Comment by pucelle** [comment]
Can't reproduce and don't know what's happening.
I made code pieces from your screenshots but can't reproduce.
Can you provide more details, like the minimum code pieces that can reproduce?

**Comment by awkj** [comment]
First, I uninstall all extension, only Keep  css-navi 
![image](https://user-images.githubusercontent.com/9017743/148752262-985a4119-f475-4733-b6a6-69693dbbc18c.png)
Second, I clear all setting 
![image](https://user-images.githubusercontent.com/9017743/148752307-46adec12-6dab-4466-ac44-5938587069e2.png)

I run 
```
pnpm create vite
select react => react-ts
```

and in App.tsx 
![image](https://user-images.githubusercontent.com/9017743/148752451-f73d7ed0-5f2b-493f-bd12-b930fac8c882.png)

**Comment by pucelle** [comment]
Sorry reply you late...
I made some codes to try to simulate the scenario in your screenshots, but I still failed to reproduce the issue.
If you have time and enough patient, could you upload a package about the files that you meed the issue?

**Comment by pucelle** [comment]
Cant reproduce......
