### ISSUE TITLE
quickSuggestions for vue files

### ISSUE THREAD

**Issue by sametsafak** [pucelle/vscode-css-navigation#65]
Hi,

When I enable quickSuggestions from settings.json as described in readme file, class suggestions doesn't show up. But if I press ctrl space, it works. Is there anything to make quickSuggestions work with vue files?

**Comment by pucelle** [comment]
In fact I don't know, this is absolutely the mechanism inside VSCode...

In my opinion you may try changing options according to: https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense
