### ISSUE TITLE
[Feature Request] Could this ext also search html/xml files with css selector ?

### ISSUE THREAD

**Issue by yw662** [pucelle/vscode-css-navigation#66]

**Comment by pucelle** [comment]
When you are typing CSS selector names, this plugin will search html files (not XML files, but you can still config the HTML like file types and include XML) for class names, tag names, ids, and provide completion.

**Comment by yw662** [comment]
我想说是，在html文件里用css选择器搜索

**Comment by pucelle** [comment]
No, The only way you can search HTML files according to a CSS Selector is "finding references" from a CSS selector in a CSS document.
