### ISSUE TITLE
Feature request - Nested .gitignore

### ISSUE THREAD

**Issue by FDiskas** [pucelle/vscode-css-navigation#7]
This solution could help you with that
https://www.npmjs.com/package/ignore-walk

**Comment by FDiskas** [comment]
```js
const walk = require('ignore-walk')

const result = walk.sync({ ignoreFiles: [ '.gitignore', '.npmignore' ] })
console.log(result);
```

**Comment by FDiskas** [comment]
It returns only not ignored files

**Comment by pucelle** [comment]
Thanks, I will research and test it in one or two days.

**Comment by pucelle** [comment]
Version `1.4.0` published, it should support nested `.gitignore`.

**Comment by FDiskas** [comment]
with 74 additions and 127 deletions. Nice

**Comment by pucelle** [comment]
😄

**Comment by pucelle** [comment]
Hi, FDiskas, I've just made some changes and release 1.8.0, now will not ignore files from `.npmignore` by default.

So if you find files listed in `.npmignore` are included, change configuration will make it work again.
