### ISSUE TITLE
Auto-completion doesn’t work in php file ?

### ISSUE THREAD

**Issue by Erghan** [pucelle/vscode-css-navigation#71]
Hi 😃,

I see there is PHP support but auto-completion in PHP page doesn't work for me.
<img width="782" alt="Capture d’écran 2022-06-28 à 17 10 38" src="https://user-images.githubusercontent.com/40079761/176215528-e4729c31-9330-49f0-afea-85fa93ae36e2.png">

In an HTML page it works fine and the rest of the features work very well but not for the auto-completion.
<img width="798" alt="Capture d’écran 2022-06-28 à 17 10 25" src="https://user-images.githubusercontent.com/40079761/176215365-6ed860ca-469f-4ecb-8cbb-dad604e73aa0.png">

I kept the configuration of this plugin by default.
I tried a few options but without success.
Is there something to do?

Other than that, this plugin is just awesome.

Sorry for my english if it is not correct...

Best regards,
Mathieu

**Comment by pucelle** [comment]
Sorry to reply you late.
I began to work on this plugin again these days.
I checked but cant reproduce, so, if this issue still matters, could you upload part of your codes here?
