### ISSUE TITLE
Got to reference should exclude current item

### ISSUE THREAD

**Issue by NoelAbrahams** [pucelle/vscode-css-navigation#86]
Hi, thanks for the extension — looks very good.

Given the following:

```css
.foo {
 width:10px;
}
```

When I right-click on `.foo` and select 'Go to References' among the items listed is this instance of `.foo` as well. The current item should be excluded from the search.

That's how it works for example TypeScript classes.

This is quite a pain point because the tool never goes to the first reference. There are always two clicks needed.

Hope this is clear?

**Comment by pucelle** [comment]
Thanks for your feedback, will work on it soon.

**Comment by pucelle** [comment]
Not luck, I found this first reference of itself is not generated by my plugin, I guess it is generated by vscode itself:
![image](https://github.com/pucelle/vscode-css-navigation/assets/9691487/70a48993-87d4-49c6-975f-16caea6c6f47)
![image](https://github.com/pucelle/vscode-css-navigation/assets/9691487/9079e41b-20c0-45f3-8225-5da8d3c9e638)

**Comment by NoelAbrahams** [comment]
Maybe worth filing this as a bug on the VSCode repository? Let me know and I can do that for you.

**Comment by pucelle** [comment]
Never mind, but I don't think this is a bug. If this behavior troubles you, filling a bug is worth it.

**Comment by NoelAbrahams** [comment]
> Not luck, I found this first reference of itself is not generated by my plugin, I guess it is generated by vscode automatically:
Are you not able to exclude that first reference?

The go-to-reference feature works correctly for TypeScript files, so there must be a way to fix this?

**Comment by pucelle** [comment]
Start an issue on vscode would be OK, only them know details.

**Comment by NoelAbrahams** [comment]
@pucelle I've opened a discussion here: https://github.com/microsoft/vscode-discussions/discussions/778

Please add any info there that you think is necessary.

**Comment by pucelle** [comment]
OK

**Comment by pucelle** [comment]
@burkeholland The first reference result, which reference current file, it not generated by this plugin, I cant see it, so its not possible to filter it out.
